name: Test

on: [pull_request]

jobs:
  test_alpine:
    name: Ruby ${{ matrix.ruby_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version: [2.4, 2.5, 2.6, 2.7, 3.0, 3.1, 3.2, 3.3]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Test on RACK_ENV=development
        run: bundle exec rake test
        env:
          RACK_ENV: development
      - name: Test on RACK_ENV=test
        run: bundle exec rake test
        env:
          RACK_ENV: test
